GET http://localhost:5000/api/logs
Accept: application/json

###
GET http://localhost:5000/api/logs?dir=tests/resources
Accept: application/json

###
GET http://localhost:5000/api/logs?file=tests/resources/file.log
Accept: application/json

###
GET http://localhost:5000/api/logs/info?file=tests/resources/file.log
Accept: application/json

###
GET http://localhost:5000/api/logs/warning?file=tests/resources/file.log
Accept: application/json

###
GET http://localhost:5000/api/logs/error?file=tests/resources/file.log
Accept: application/json

###
GET http://localhost:5000/api/logs/error?file=tests/resources/file.log&nlines=3
Accept: application/json

###